import { describe, it, expect } from 'vitest';
import { createRoom, act, assess, calculate, view, tick, canDistill, winners, botPlan, type Room, type Plan } from '../shared/game';
const good: Plan = { brief: 0, model: 'compact', data: 2, training: 1, evaluation: 0, distill: false, release: 'research' };
function room() { const r = createRoom('ABC234', 'a', 'First Lab', 0); act(r, 'b', { type: 'join', name: 'Second Lab' }, 0); act(r, 'a', { type: 'start' }, 1); return r; }
function bid(r: Room, a = 0, b = 0) { act(r, 'a', { type: 'bid', round: r.round, phase: 'bid', bid: a }, 2); act(r, 'b', { type: 'bid', round: r.round, phase: 'bid', bid: b }, 2); }
describe('authoritative gameplay', () => {
  it('matches the approved worked examples', () => { const r = room(); bid(r); expect(assess(r, r.players[0], good)).toMatchObject({ ratings: { accuracy: 5, efficiency: 3, reliability: 3 }, cost: 6, impact: 4 }); expect(assess(r, r.players[0], { ...good, brief: 1, model: 'balanced', training: 0, evaluation: 2 })).toMatchObject({ cost: 8, impact: 4, ratings: { accuracy: 5, efficiency: 2, reliability: 5 } }); expect(assess(r, r.players[0], { ...good, brief: 2, model: 'large', training: 0 })).toMatchObject({ cost: 7, impact: 0, success: false }); });
  it('awards tied compute fairly with rotating priority and charges only winners', () => { const r = room(); bid(r, 2, 2); expect(r.players.map(p => [p.bonus, p.credits])).toEqual([[true, 10], [false, 12]]); act(r, 'a', { type: 'build', round: 1, phase: 'build', plan: good }, 3); act(r, 'b', { type: 'build', round: 1, phase: 'build', plan: good }, 3); for (const id of ['a','b']) act(r, id, { type: 'upgrade', round: 1, phase: 'reveal', upgrade: null }, 4); bid(r, 2, 2); expect(r.players.map(p => p.bonus)).toEqual([false,true]); });
  it('keeps opponents’ submissions and bids out of serialized views', () => { const r = room(); act(r, 'a', { type: 'bid', round: 1, phase: 'bid', bid: 3 }, 2); const rival = view(r, 'b', 2, 'local'); expect(rival.players[0]).not.toHaveProperty('bid'); expect(rival.me.bid).toBeUndefined(); bidRemaining(); function bidRemaining() { act(r, 'b', { type: 'bid', round: 1, phase: 'bid', bid: 0 }, 2); } act(r, 'a', { type: 'build', round: 1, phase: 'build', plan: good }, 3); expect(view(r, 'b', 3, 'local').players[0]).not.toHaveProperty('plan'); expect(view(r, 'b', 3, 'local').me.plan).toBeUndefined(); });
  it('rejects overspending, invalid levels, foreign members, and duplicate bids', () => { const r = room(); expect(() => act(r, 'outsider', { type:'start' }, 2)).toThrow('Join'); expect(() => act(r, 'b', { type:'start' }, 2)).toThrow('Only'); act(r, 'a', { type:'bid', round:1, phase:'bid', bid:0 }, 2); expect(() => act(r, 'a', { type:'bid', round:1, phase:'bid', bid:0 }, 2)).toThrow('locked'); act(r, 'b', { type:'bid', round:1, phase:'bid', bid:0 }, 2); expect(() => act(r,'a',{ type:'build',round:1,phase:'build',plan:{...good,data:3}},3)).toThrow('levels'); r.players[0].credits = 1; expect(() => act(r,'a',{ type:'build',round:1,phase:'build',plan:good},3)).toThrow('credits'); });
  it('counts auction spending against the efficiency cost stretch', () => { const r = room(); bid(r,3,0); const plan = {...good, brief:2, model:'balanced' as const, training:1}; expect(assess(r,r.players[0],plan)).toMatchObject({ cost:10, success:true, stretch:false, impact:3 }); });
  it('fails the entire brief if a mandatory condition is missed', () => { const r = room(); bid(r); const plan = {...good, model:'large' as const, data:0, training:0}; act(r,'a',{type:'build',round:1,phase:'build',plan},3); act(r,'b',{type:'build',round:1,phase:'build',plan:good},3); expect(r.players[0]).toMatchObject({ credits:9,research:0,impact:0,completed:0 }); });
  it('unsubmitted phases time out without freezing the match', () => { const r=room(); expect(tick(r,45002)).toBe(true); expect(r.phase).toBe('build'); tick(r,165003); expect(r.phase).toBe('reveal'); expect(r.players.every(p=>p.results[0].impact===0)).toBe(true); tick(r,255004); expect(r.round).toBe(2); expect(r.players[0].credits).toBe(17); });
  it('upgrades apply next round and research dissemination is delayed', () => { const r=room(); bid(r); for(const id of ['a','b']) act(r,id,{type:'build',round:1,phase:'build',plan:good},3); act(r,'a',{type:'upgrade',round:1,phase:'reveal',upgrade:'distillation'},4); expect(r.discoveries.distillation).toBe(3); act(r,'b',{type:'upgrade',round:1,phase:'reveal',upgrade:'pipeline'},4); expect(r.round).toBe(2); expect(canDistill(r,r.players[0])).toBe(true); expect(canDistill(r,r.players[1])).toBe(false); expect(calculate(r.players[1],good).cost).toBe(5); r.round=3; expect(canDistill(r,r.players[1])).toBe(true); });
  it('finishes six rounds without automatic reset and supports a clean rematch', () => { const r=room(); for(let round=1;round<=6;round++) { bid(r); for(const p of r.players) act(r,p.id,{type:'build',round,phase:'build',plan:botPlan(r,p)},round*10); if(round<6) for(const p of r.players) act(r,p.id,{type:'upgrade',round,phase:'reveal',upgrade:null},round*10+1); } expect(r.phase).toBe('finished'); expect(r.round).toBe(6); expect(r.players.every(p=>p.results.length===6 && p.impact<=24)).toBe(true); expect(winners(r)).toHaveLength(2); act(r,'a',{type:'rematch'},100); expect(r.phase).toBe('lobby'); expect(r.players.every(p=>p.credits===12 && p.impact===0 && p.results.length===0)).toBe(true); });
  it('rejects stale phase actions and requires a disconnected host for takeover',()=>{const r=room();bid(r);expect(()=>act(r,'a',{type:'build',round:2,phase:'build',plan:good},3)).toThrow('phase changed');expect(()=>act(r,'b',{type:'claim-host'},3)).toThrow('connected');act(r,'b',{type:'claim-host'},80000);expect(r.host).toBe('b');});
  it('caps rooms at eight players and prevents joins during matches',()=>{const r=createRoom('ABC234','a','Alpha',0);for(let n=1;n<8;n++)act(r,String(n),{type:'join',name:`Lab ${n}`},1);expect(()=>act(r,'extra',{type:'join',name:'Extra'},1)).toThrow('full');act(r,'a',{type:'start'},2);expect(()=>act(r,'extra',{type:'join',name:'Extra'},3)).toThrow('started');});
});
