import { useState } from 'react';
import { Image, MessageSquare, FileText, Database, Cpu, Wrench, Check, X, FlaskConical, Building2, Minus, Plus } from 'lucide-react';
import { MODELS, assess, calculate, canDistill, type Plan, type View } from '../../shared/game';
import type { Action } from '../../shared/game';
import { Roster } from './Match';
const icons = [Image, MessageSquare, FileText];
export function Stepper({ title, description, value, change, icon: Icon }: { title: string; description: string; value: number; change: (n: number) => void; icon: typeof Cpu }) {
  return <div className="stepper"><Icon size={22}/><div><strong>{title}</strong><small>{description}</small></div><div className="step-controls"><button aria-label={`Decrease ${title}`} disabled={value === 0} onClick={() => change(value - 1)}><Minus size={16}/></button><output aria-label={`${title} level`}>{value}</output><button aria-label={`Increase ${title}`} disabled={value === 2} onClick={() => change(value + 1)}><Plus size={16}/></button></div></div>;
}
export function Build({ v, action, busy }: { v: View; action: (a: Action) => Promise<void>; busy: boolean }) {
  const [plan, setPlan] = useState<Plan>(v.me.plan ?? { brief: 0, model: 'compact', data: 0, training: 0, evaluation: 0, distill: false, release: 'commercial' });
  const [confirm, setConfirm] = useState(false);
  const p = v.me, b = v.briefs[plan.brief], preview = assess(v, p, plan), { cost, ratings } = calculate(p, plan);
  const affordable = cost <= p.credits;
  const set = (patch: Partial<Plan>) => { setConfirm(false); setPlan(old => ({ ...old, ...patch })); };
  if (p.plan) return <div className="waiting"><FlaskConical size={42}/><h2>Model submitted.</h2><p>Your choices are locked. The field trials reveal when everyone submits or the timer ends.</p><div className="submitted"><strong>{v.briefs[p.plan.brief].name}</strong><span>{MODELS[p.plan.model].name} · {p.plan.release === 'research' ? 'Open research' : 'Commercial release'}</span></div><p className="muted">{v.buildLocked.length} / {v.players.length} labs submitted</p></div>;
  return <div className="build-grid"><section className="build-work"><h2 className="section-label">01 <span>Choose a brief</span></h2><div className="briefs">{v.briefs.map((brief, i) => { const Icon = icons[i]; return <button key={brief.name} className={`brief ${plan.brief === i ? 'selected' : ''}`} aria-pressed={plan.brief === i} onClick={() => set({ brief: i })}><div className="brief-title"><Icon size={23}/><strong>{brief.name}</strong><span className="radio"/></div><p>{brief.description}</p><dl>{Object.entries(brief.target).map(([key, val]) => <div key={key}><dt>{key}</dt><dd>{val}+</dd></div>)}</dl><small>Stretch: {brief.stretch.stat === 'cost' ? `spend ≤${brief.stretch.value}` : `${brief.stretch.stat} ≥${brief.stretch.value}`} <span>+1 Impact</span></small></button>; })}</div>
    <h2 className="section-label">02 <span>Choose your model</span></h2><div className="models">{Object.entries(MODELS).map(([key, m]) => <button aria-pressed={plan.model === key} className={plan.model === key ? 'selected' : ''} key={key} onClick={() => set({ model: key as Plan['model'] })}><div><strong>{m.name}</strong><span className="mono">{m.cost} cr</span></div><small>{m.description}</small><span className="model-stats">ACC {m.accuracy} / EFF {m.efficiency} / REL {m.reliability}</span></button>)}</div>
    <h2 className="section-label">03 <span>Allocate your effort</span></h2><div className="steppers"><Stepper title="Better data" description={p.upgrades.includes('pipeline') ? '+1 Accuracy & Reliability · first level 1 cr' : '+1 Accuracy & Reliability · 2 cr / level'} value={plan.data} change={n => set({ data: n })} icon={Database}/><Stepper title="More training" description={`+1 Accuracy · 1 cr / level${p.bonus ? ' · bonus accelerator adds +1 free' : ''}`} value={plan.training} change={n => set({ training: n })} icon={Cpu}/><Stepper title="Evaluation & fixes" description={p.upgrades.includes('bench') ? '+1 Reliability · first level free' : '+1 Reliability · 1 cr / level'} value={plan.evaluation} change={n => set({ evaluation: n })} icon={Wrench}/>{canDistill(v, p) ? <label className="technique"><input type="checkbox" checked={plan.distill} onChange={e => set({ distill: e.target.checked })}/><div><strong>Distillation</strong><small>+2 Efficiency · 1 credit</small></div></label> : null}</div>
    <h2 className="section-label">04 <span>Choose your release</span></h2><div className="releases"><button aria-pressed={plan.release === 'commercial'} className={plan.release === 'commercial' ? 'selected' : ''} onClick={() => set({ release: 'commercial' })}><Building2 size={23}/><div><strong>Commercial</strong><small>Success: +6 credits, +1 research</small></div><span className="radio"/></button><button aria-pressed={plan.release === 'research'} className={plan.release === 'research' ? 'selected' : ''} onClick={() => set({ release: 'research' })}><FlaskConical size={23}/><div><strong>Open research</strong><small>Success: +2 credits, +3 research</small></div><span className="radio"/></button></div>
  </section><div className="lab-aside"><aside className="preview"><h2><FlaskConical size={20}/>Laboratory summary</h2><div className="wallet"><div><small>Credits</small><strong>{p.credits}</strong></div><div><small>Research</small><strong>{p.research}</strong></div><div><small>Impact</small><strong>{p.impact}</strong></div></div><h3>Model performance</h3><div className="rating-bars">{Object.entries(ratings).map(([k, val]) => <div key={k}><span>{k}</span><div className="bar"><i style={{ width: `${Math.min(100, val / 8 * 100)}%` }}/></div><strong>{val}</strong></div>)}</div><h3>Requirements</h3><div className="checks">{Object.entries(b.target).map(([k, val]) => { const okay = ratings[k as keyof typeof ratings] >= val; return <div className={okay ? 'good' : 'bad'} key={k}>{okay ? <Check size={16}/> : <X size={16}/>}<span>{k} ≥{val}</span></div>; })}<div className={preview.stretch ? 'good' : 'muted'}><span>✧</span><span>{preview.stretch ? 'Stretch target met' : 'Stretch target not met'}</span></div></div><div className="prediction"><span>Projected Impact</span><strong>{preview.impact}<small> / 4</small></strong></div><div className={`cost ${!affordable ? 'bad' : ''}`}><span>Build cost</span><strong>{cost} / {p.credits} cr</strong></div>{p.bidPaid ? <p className="tiny">Auction already paid: {p.bidPaid} cr. Total experiment spend: {cost + p.bidPaid} cr.</p> : null}<button className="primary submit" disabled={!affordable || busy} onClick={async () => { if (!preview.success && !confirm) { setConfirm(true); return; } await action({ type: 'build', plan }); }}><FlaskConical size={18}/>{busy ? 'Submitting…' : confirm ? 'Submit failing model anyway' : 'Submit model'}</button>{confirm ? <p role="alert" className="error">This plan misses a required target and earns 0 Impact. Adjust it or confirm.</p> : <p className="tiny">Exact simulated result. Choices lock on submission.</p>}</aside><Roster v={v}/></div></div>;
}
