import { useCallback, useEffect, useRef, useState } from 'react';
import { Copy, Clock, LogOut } from 'lucide-react';
import { ERAS, type View, type Action } from '../shared/game';
import * as client from './client';
import { Entry } from './components/Entry';
import { Build } from './components/Build';
import { Lobby, Auction, Results } from './components/Match';
import { Rules } from './components/Rules';
export default function App() {
  const [v, setV] = useState<View | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [rules, setRules] = useState(false); const [restoring, setRestoring] = useState(true); const [online, setOnline] = useState(true); const [seconds, setSeconds] = useState(0); const [copied, setCopied] = useState(false);
  const current = useRef<View | null>(null); const polling = useRef(false);
  const accept = useCallback((next: View) => { const old = current.current; if (old && old.code === next.code && old.revision > next.revision) return; current.current = next; setV(next); sessionStorage.setItem('labwars.room', next.code); setOnline(true); }, []);
  const poll = useCallback(async (code: string) => { if (polling.current) return; polling.current = true; try { const next = await client.refresh(code); if (current.current?.code === code) accept(next); } catch { setOnline(false); } finally { polling.current = false; } }, [accept]);
  useEffect(() => { let cancelled = false; const code = sessionStorage.getItem('labwars.room'); void client.initialize().then(async () => { if (code) { try { const next = await client.refresh(code); if (!cancelled) accept(next); } catch { sessionStorage.removeItem('labwars.room'); } } }).catch(e => { if (!cancelled) setError((e as Error).message); }).finally(() => { if (!cancelled) setRestoring(false); }); return () => { cancelled = true; }; }, [accept]);
  useEffect(() => { if (!v) return; const code = v.code; const interval = setInterval(() => void poll(code), 2500); const unsubscribe = client.subscribe(code, () => void poll(code)); const visible = () => { if (document.visibilityState === 'visible') void poll(code); }; window.addEventListener('online', visible); document.addEventListener('visibilitychange', visible); return () => { clearInterval(interval); unsubscribe(); window.removeEventListener('online', visible); document.removeEventListener('visibilitychange', visible); }; }, [v?.code, poll]);
  useEffect(() => { if (!v) return; const offset = v.serverNow - Date.now(); const update = () => setSeconds(Math.max(0, Math.ceil((v.deadline - (Date.now() + offset)) / 1000))); update(); const timer = setInterval(update, 500); return () => clearInterval(timer); }, [v?.deadline, v?.serverNow]);
  async function action(a: Action) { if (!v || busy) return; setBusy(true); setError(''); try { accept(await client.send(v.code, { round: v.round, phase: v.phase, ...a })); } catch (e) { setError((e as Error).message); void poll(v.code); } finally { setBusy(false); } }
  function leave() { sessionStorage.removeItem('labwars.room'); current.current = null; setV(null); setError(''); }
  const phaseTitle = v?.phase === 'bid' ? 'Secure your compute' : v?.phase === 'build' ? 'Build your next model' : 'Field trials';
  return <div className="app-shell"><header className="app-header"><div className="brand">LAB <span>WARS</span><small>Neural Foundry</small></div>{v && v.round > 0 ? <div className="round-track" aria-label={`Round ${v.round} of 6`}>{[1,2,3,4,5,6].map(n => <div key={n} className={v.round === n ? 'active' : v.round > n ? 'complete' : ''}><span>{n}</span><small>Round {n}</small></div>)}</div> : <span className="header-note">Build something worth shipping.</span>}<div className="header-actions">{v ? <button className="room-button" onClick={async () => { try { await navigator.clipboard.writeText(v.code); setCopied(true); setTimeout(() => setCopied(false), 1800); } catch { setError(`Room code: ${v.code}`); } }}><span>{copied ? 'Copied' : `Room ${v.code}`}</span><Copy size={15}/></button> : null}<button onClick={() => setRules(true)}>Rules</button>{v ? <button className="icon-button" aria-label="Leave room" onClick={leave}><LogOut size={16}/></button> : null}</div></header>
    {error ? <div className="error-banner" role="alert">{error}<button onClick={() => setError('')} aria-label="Dismiss error">×</button></div> : null}
    {restoring ? <main className="waiting"><h1>Opening the lab…</h1></main> : !v ? <Entry enter={accept} rules={() => setRules(true)}/> : <main className="match-main">{!online ? <div className="connection-banner" role="status">Reconnecting. Your locked choices are saved.<button onClick={() => poll(v.code)}>Retry</button></div> : null}{v.phase !== 'lobby' && v.phase !== 'finished' ? <div className="phase-heading"><div><p className="phase-meta">ROUND {v.round} / 6 <span>{ERAS[v.round - 1]}</span></p><h1>{phaseTitle}</h1><p className="muted">{v.phase === 'build' ? 'Choose the right approach. Meet the brief. Decide how to release.' : v.phase === 'bid' ? 'Everyone bids in secret. Winners earn a training advantage.' : 'Compare your results and prepare your lab for what comes next.'}</p></div><div className={`timer ${seconds < 15 ? 'urgent' : ''}`}><Clock size={16}/><strong>{Math.floor(seconds / 60)}:{String(seconds % 60).padStart(2, '0')}</strong></div></div> : null}
      {v.phase === 'lobby' ? <Lobby v={v} action={action} busy={busy}/> : v.phase === 'bid' ? <Auction key={`bid-${v.round}`} v={v} action={action} busy={busy}/> : v.phase === 'build' ? <Build key={`build-${v.round}`} v={v} action={action} busy={busy}/> : <Results v={v} action={action} busy={busy}/>}
      {v.players.find(p => p.id === v.host) && v.host !== v.me.id && Date.now() - v.players.find(p => p.id === v.host)!.lastSeen > 75000 ? <button className="text-button" disabled={busy} onClick={() => action({ type: 'claim-host' })}>Host disconnected · take over hosting</button> : null}
    </main>}<footer><span>NEURAL FOUNDRY</span><span>{v ? `${v.players.some(p => p.bot) ? 'Practice match' : 'Multiplayer match'} · ${v.phase === 'finished' ? 'Complete' : online ? 'Connected' : 'Reconnecting'}` : 'Small labs. Big decisions.'}</span></footer>{rules ? <Rules close={() => setRules(false)}/> : null}</div>;
}
